# Generated by Django 5.1.7 on 2025-03-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_recipe_created_on_recipe_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
