# Generated by Django 5.1.7 on 2025-03-10 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_recipe_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='inRecipe',
            new_name='in_Recipe',
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='ingredientType',
            new_name='ingredient_Type',
        ),
    ]
