# Generated by Django 5.1.7 on 2025-03-24 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_recipeimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeimage',
            old_name='image_in_Recipe',
            new_name='belongs_to_recipe',
        ),
    ]
